title: The Missing Soft.Eng Course
description: An online workbook for Them Missing Soft.Eng Course
theme: just-the-docs

url: https://keshvadi.github.io

aux_links:
  Sina Keshvadi: https://keshvadi.github.io
# color_scheme: dark
color_scheme: custom
