title: The Shell
description: An online workbook for learning The Shell
theme: just-the-docs

url: https://keshvadi.github.io

aux_links:
  Sina Keshvadi: https://keshvadi.github.io
# color_scheme: dark
color_scheme: custom
